### ISSUE TITLE
Shouldn't `<gallery ...>` Tag be filtered by clean_value  ?

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#200]
In the French Wikipedia dump of the article about "Arabie saoudite", there is 
```
<gallery mode="packed-hover">
Fichier:Flickr - omar chatriwala - Dawn breaks.jpg|[[Médine (province)|Médine]].
Fichier:Buraidah.jpg|[[Al Qasim]].
Fichier:Hai'l city.jpg|[[Haïl (province)|Haïl]].
Fichier:جبل حرفة في بني عمرو.jpg|[[Asir (province)|Asir]].
Fichier:بحر حقل (15037998121).jpg|[[Tabuk (province)|Tabuk]].
Fichier:Origineel huis Najran.JPG|[[Najran (province)|Najran]].
Fichier:Makkah-Panorama-2011.jpg|[[La Mecque (province)|La Mecque]].
Fichier:Faifa city.jpg|[[Jizan (province)|Jizan]].
</gallery>
```

product this output 
```
Fichier:Flickr - omar chatriwala - Dawn breaks.jpg|Médine.
Fichier:Buraidah.jpg|Al Qasim.
Fichier:Hai'l city.jpg|Haïl.
Fichier:جبل حرفة في بني عمرو.jpg|Asir.
Fichier:بحر حقل (15037998121).jpg|Tabuk.
Fichier:Origineel huis Najran.JPG|Najran.
Fichier:Makkah-Panorama-2011.jpg|La Mecque.
Fichier:Faifa city.jpg|Jizan.
```

Shouldn't `<gallery ...>` Tag be filtered by clean_value  ?

**Comment by kristian-clausal** [comment]
The gallery 'tag' is filtered, but not its contents. Wiktionary doesn't seem to use this wikitext tag (at all?), so this is just an oversight. I'll take a look at it.

**Comment by kristian-clausal** [comment]
Ok, in this case I think we will leave the current stuff as-is, because it would need changing clean_node() in Wiktextract. The 'correct' way to do this is like this:

```python

from wikitextprocessor import Wtp, NodeKind, WikiNode
from wikitextprocessor.parser import print_tree
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig
from wiktextract.page import clean_node

wtp = Wtp(
    db_path="frwp-wikt.db",
    lang_code="fr",
    project="wikipedia",
)

wxr = WiktextractContext(wtp, WiktionaryConfig())

wiki_page_body = """Should be visible <gallery>SHOULD NOT BE VISIBLE</gallery>"""
wiki_page_title = "Test"

wxr.wtp.start_page(wiki_page_title)
wiki_data = wxr.wtp.parse(
    text=wiki_page_body,
    expand_all=True,
)

print_tree(wiki_data, 2)

def clean_node_handler_fn(node):
    """Process nodes when encountering them; for example
    by filtering them or changing them if needed."""
    assert isinstance(node, WikiNode)
    kind = node.kind
    if kind in {
        NodeKind.TABLE_CELL,
        NodeKind.TABLE_HEADER_CELL,
    }:
        return node.children
    if kind == NodeKind.HTML and node.sarg == "gallery":
        return []
    return None

text = wxr.wtp.node_to_html(
    wiki_data,
    node_handler_fn=clean_node_handler_fn
)

print(text)
```

clean_node() is a Wiktextract (Wiktionary parsing) specific implementation of a node-cleaning function that should be forked and modified in this case, OR I guess we could add a parameter for the node-handling function that would be passed on to wtp.node_to_html().

The 'correct' way to do this is roughly what is above: Wtp.node_to_html() (which goes through several layers of functions, it's not just HTML, the HTML is just the 'final' step before clean_values removes everything with regex and string manipulation) has a parameter that takes a function. The function is usually pretty barebones, I think, in clean_node() it just removes some table stuff (returning contents); if the function returns None, it means 'don't do anything' with the result of the function and process the node as normal, so by returning an empty list (or string, too, I guess?) we can just filter out the `gallery` elements.

I'll ask Tatu about adding a new parameter to clean_node for convenience that takes this cleaning function, shouldn't be too hard, just a bit messy because we have too many functions with huge amounts of parameters...

**Comment by kristian-clausal** [comment]
Just realized a bit of clean_node() seems to be a fossil function (`recurse()`) which is never called, so if you see a commit about changing clean_node() I'm just cleaning things up. This also makes it easier to copy the functionality of clean_node() for other purposes.

**Comment by LeMoussel** [comment]
Sorry, I'm having some difficulty identifying whether this is the responsibility of `wikitextprocessor` or `Wiktexttract`.
If you agree, I suggest you create the issues here and then indicate whether this is a `Wiktexttract` anomaly or not.

**Comment by kristian-clausal** [comment]
Wiktextract is specifically for parsing Wiktionary data, so it shouldn't really take responsibility for this, and Wikitextprocessor is very bare bones on purpose. Currently, 'technically' there should be a fork for when you want to do things differently from Wiktextract is doing, but other solutions make more sense (like moving the cleaning stuff, maybe).

**Comment by LeMoussel** [comment]
Agree with you that the cleanup functions (and perhaps others) should be in `wikitextprocessor`.

**Comment by kristian-clausal** [comment]
Anyhow, this issue does not seem to be necessary anymore, so I'll be closing it.
