### ISSUE TITLE
ERROR: unimplemented parserfn filepath

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#224]
On Wikipedia [Global Positioning System](https://fr.wikipedia.org/wiki/Global_Positioning_System) page, there is this error:
`
 ERROR: unimplemented parserfn filepath at ['Global Positioning System', 'Comparaison des orbites des satellites de navigation', 'filepath', 'filepath']
`

The Wikitext template is: `{{Comparaison des orbites des satellites de navigation}}`
I don't see what this is for, because nothing is displayed on the HTML page.

```python
from unittest import TestCase

from wikitextprocessor import Wtp
from wiktextract.page import clean_node
from wiktextract.wxr_context import WiktextractContext
from wiktextract.config import WiktionaryConfig


class TestFilepath(TestCase):
    def setUp(self):
        self.wxr = WiktextractContext(
            wtp = Wtp(
                db_path="fr-wiki-latest.db",
                lang_code="fr",
                project="wikipedia",
            ),
            config=WiktionaryConfig()
        )

    def tearDown(self):
        self.wxr.wtp.close_db_conn()

    def test_filepath(self):
        self.wxr.wtp.start_page("Test filepath")
        tree = self.wxr.wtp.parse(text="{{Comparaison des orbites des satellites de navigation}}", expand_all=True)
        text = clean_node(
            wxr=self.wxr,
            sense_data={},
            wikinode=tree,
        )
        self.assertGreater(len(text), 0)
```

**Comment by LeMoussel** [comment]
I haven't found much information on `filepath` just this https://www.mediawiki.org/wiki/Help:Magic_words#URL_data

**Comment by LeMoussel** [comment]
I suggest this correction in [parsefn.py](https://github.com/tatuylonen/wikitextprocessor/blob/main/src/wikitextprocessor/parserfns.py#L1526)
```python
....
    "filepath": filepath_fn, #unimplemented_fn,
....

def filepath_fn(
    ctx: "Wtp", fn_name: str, args: list[str], expander: Callable[[str], str]
) -> str:
    """Implements the #filepath parser function."""
    assert isinstance(args, dict)
    # We don't currently really implement filepath.
    # It is just recognized and silently ignored.
    return ""
```

**Comment by kristian-clausal** [comment]
#parserfn seems to return two kinds of return values: string (empty string or the url, either full url, or maybe relative url, and then there's `//url/` 'protocol relative url', which I *guess* means it's an url that copies the protocol prefix, like 'http:' or 'https:'...) or a PHP array -> Lua table -> Python dict with the url and a field 'nowiki' set to true. Gotta try to find out if that's just `{1: url, "nowiki": True}`...

It gets basically three arguments, {{parserfn:filename|nowiki|width}} or {{parserfn:filename|width|nowiki}} with any of `nowiki` and `width` left out. The width is used to create thumbnails, so we can ignore it (unless it turns out some silly bit of code somewhere validates the stupid filename to check if it really looks like a thumbnail for some reason, even if it's already passed the parameter to parserfn and really should know already grumble grumble), we can check if either of arguments 1 or 2 is 'nowiki' to return the dict, otherwise return some kind of dummy url, like `//unimplemented/filename`.

The filename thing is interesting, because what happens if that there's an actual search for a file named by the `filename`, and its url is returned. No idea how that works in practice -- no duplicate filenames allowed?

**Comment by kristian-clausal** [comment]
Except I have no why the parser function PHP code returns an array. AFAIK, as far as the code knows, parserfns return only strings (and testing it on Wikipedia's (not Wiktionary, doesn't work there, but that's a different can of worms that doesn't really seem urgent ever) sandbox just returns strings)...

After trying to figure out, even though it looks like it should, `nowiki` doesn't do anything that I can discern (result is the same string), we can ignore width, and either we always should fail the process (always return empty string) or always succeed (always return an "//unimplemented/filename.jpg" string to signal that there was something there...).

I think I might just implement the dummy string return.

**Comment by LeMoussel** [comment]
_and testing it on Wikipedia's_
Could you explain to me how to test on Wikipedia?
So, I hope I can help you by providing you with some testing information on Wikipedia.

**Comment by kristian-clausal** [comment]
Oh, I just opened https://en.wikipedia.org/w/index.php?title=Wikipedia:Sandbox&action=edit and typed in `{{filepath: blah blah blah}}` in different configurations. Just to see what happens, same as when trying to figure out how a piece of Wikitext syntax actually should behave: "what if I add a space here?" kinds of testing.

**Comment by LeMoussel** [comment]
Anomaly resolved
