### ISSUE TITLE
Infinite loop during `clean_node()`

### ISSUE THREAD

**Issue by LeMoussel** [tatuylonen/wikitextprocessor#233]
There I think I came across "a bone" :)
Indeed `clean_node()` seems to loop on this page [Association francophone des utilisateurs de logiciels libres](https://fr.wikipedia.org/wiki/Association_francophone_des_utilisateurs_de_logiciels_libres)
I have the display below which is displayed continuously.

![image](https://github.com/tatuylonen/wikitextprocessor/assets/1816573/ab3b160f-2619-42c6-87d3-94939c9ba6a9)

Test code:
```python
    wtp = Wtp(
            db_path="fr-wiki-latest.db",
            lang_code="fr",
            project="wikipedia",
    )
    wxr = WiktextractContext(wtp, WiktionaryConfig())

    wiki_page = wxr.wtp.get_page('Association francophone des utilisateurs de logiciels libres')
    wxr.wtp.start_page(wiki_page.title)
    wiki_nodes = wxr.wtp.parse(text=wiki_page.body)
    text = clean_node(
            wxr=wxr,
            sense_data={},
            wikinode=wiki_nodes,
            collect_links=False,
        )

    info_log = ''
    if len(wxr.wtp.errors) > 0:
        info_log += f"{wiki_page.title}: {len(wxr.wtp.errors)} ERR"
    elif len(wxr.wtp.warnings) > 0:
        if info_log == '':
            info_log += f"{wiki_page.title}: {len(wxr.wtp.warnings)} WARN"
        else:
            info_log += f", {len(wxr.wtp.warnings)} WARN"
    print(info_log)
```

**Comment by xxyzz** [comment]
Similar to #193 but this error is caused by the `<nowiki>` tag, the code should replace the `<nowiki>` tags in the template body before call `Wtp._encode()`.

The above commit should fix this error but can't pass the [test_html_end_tag_in_parserfn](https://github.com/tatuylonen/wikitextprocessor/blob/4e3a46b3c2a086b173466f1c3b8818597058ac0e/tests/test_parser.py#L2688-L2697) text, because the nowiki check at here is too simple and incorrect(like #180): https://github.com/tatuylonen/wikitextprocessor/blob/4e3a46b3c2a086b173466f1c3b8818597058ac0e/src/wikitextprocessor/core.py#L655
