### ISSUE TITLE
Differences between Lua versions : Invalid escape sequence near '".+\/'

### ISSUE THREAD

**Issue by leyan** [tatuylonen/wikitextprocessor#31]
I am trying to adapt wiktword to work on the French wiktionary. While doing that, I ran into an issue inside wikitextprocessor which seems to come from the different Lua versions used: 

* This module here https://fr.wiktionary.org/wiki/Module:locution uses `titre = mw.ustring.gsub(titre, ".+\/", "")`
* This works on Lua 5.1
* However, it gives an error on Lua 5.4.4 `invalid escape sequence near '".+\/'`

I saw already quite a lot of substitutions made on luaexec.py, is it a case of adding another? I added `[r"\\/", r"/"]` to the list and the error disappeared, but I am not sure if it is the correct way of solving it and I don't know Lua so I don't know what changed between 5.1 and 5.4.

**Comment by kristian-clausal** [comment]
I think this is actually a... Not a bug, but unnecessary escape in the original module: I am pretty sure `".+/"` is the correct way to do it, because / is not a special character that needs to be escaped. It's just that 5.1 let's you escape a ton of stuff just in case..? This then makes 5.4 panic, because it's not a valid escape sequence.

I've just added a regex to fix this temporarily.

I've gotten as an assignment to try to migrate us from the pip version of Lupa to changing everything to use a git repo version, so when I mean "temporarily" I really mean it (fingers crossed).
